[package]
name = "line-density"
version = "0.2.0"
authors = ["Dominik Moritz <domoritz@gmail.com>"]
edition = "2024"

[dependencies]
imageproc = "0.25"
image = "0.25.0"
rand = "0.4.2"
palette = "0.3.0"
rayon = "1.10.0"
